version: 2

sources:
  - name: AIRBYTE_DATABASE
    description: 'db for codetest'
    database: AIRBYTE_DATABASE
    schema: AIRBYTE_SCHEMA
    tables:
      - name: PEOPLE
        description: 'details about people'
        columns:
          - name: person_id
            description: "primary key for this table"
            tests: 
              - unique
              - not_null 
          - name: place_of_birth
        tests:
          - relationships:
              to: ref('places')
              field: city
      - name: PLACES
        description: 'details about places'
        columns:
          - name: city_id
            description: "primary key for this table"
            tests: 
              - unique
              - not_null 